theme = "hugo-theme-stack"
baseURL = "http://gradcylinder.org/"
languageCode = "en-us"
title = "The Graduated Cylinder"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]